### ISSUE TITLE
Dated Space

### ISSUE THREAD

**Issue by torgo** [w3ctag/spec-reviews#102]
There has been some [feedback](https://twitter.com/tobie/status/695986377767444481) from the [community](https://twitter.com/briankardell/status/696132998220140545) regarding the directory structure in this repository. The proposal is to migrate away from dated space but preserve the links in some way. /cc @bkardell @tobie @domenic @marcoscaceres

**Comment by mnot** [comment]
Good to know we're on top of the big issues.

**Comment by marcoscaceres** [comment]
To be fair, I'm sure I'm not alone in having dropped into this repo wanting to read a TAG review and giving up upon seeing the year directories. 

It would be great to see them at a glance, even in the README. That could quite easily be included.

**Comment by torgo** [comment]
I am just trying to channel the collective zeitgeist of the community, @mnot.

**Comment by mnot** [comment]
The repo is a bit weird, in that 90%+ of the reviews are *not* done as files there; they're done in the issues. We state that we prefer to give feedback in WGs' own channels, rather than making them come here.

It's more a collection of things that needed more complex writing before we handed them to WGs -- although even then we sometimes don't use the repo.

So we shouldn't imply that the collection here is meaningful or complete; they're just places where we do some work (as all of the TAG github space is).

That's why I suggested using the wiki instead on Twitter.

**Comment by chaals** [comment]
> It would be great to see them at a glance, even in the README. That could quite easily be included.

Yeah, having a list of the reviews done, even if it ends up as pointers to other places, would be really helpful for people trying to distill out of them some guidance …

**Comment by torgo** [comment]
Alex has agreed to restructure the repo and maintain links using redirects.

**Comment by torgo** [comment]
@dbaron points out in the call today: we should use spec short names consistently.

**Comment by tobie** [comment]
:+1:

**Comment by domenic** [comment]
> and maintain links using redirects.

How?

**Comment by tobie** [comment]
You're completely spoiling this @domenic. I was so looking forward to see @slightlyoff plow his way through the github documentation before arriving at the same conclusion.

**Comment by marcoscaceres** [comment]
Just use my PR, and stop using the dated space. Done. 💃
