### ISSUE TITLE
Generic Sensor API

### ISSUE THREAD

**Issue by tobie** [w3ctag/spec-reviews#110]
Would <3 a review of the [Generic Sensor API](https://w3c.github.io/sensors/) and [Ambient Light Sensor](https://w3c.github.io/ambient-light/) specs. The latter is defined in terms of the former, and as we have plenty more in the pipeline (gyroscope, magnetometer, accelerometer, altimeter, etc.), I'd rather we get it right early in the process (so there are still some rough edges, please bear with me).

@riju is planning to file an _"Intent to Implement"_ to the Blink mailing list shortly and has a working prototype of the AmbientLightSensor API already.

**Comment by torgo** [comment]
Taken up at [London F2F](https://github.com/w3ctag/meetings/blob/gh-pages/2016/03-london/agenda.md). @travisleithead will “take a look at it.” @torgo will take a look as well.

**Comment by torgo** [comment]
Split out the Ambient Light Sensor API review into #115.

**Comment by tobie** [comment]
I can't seem to find call details anywhere. How can I join the call and at what time is it?

**Comment by travisleithead** [comment]
[Agenda with details is here](https://github.com/w3ctag/meetings/blob/gh-pages/2016/telecons/04-20-agenda.md)

**Comment by travisleithead** [comment]
Overall, very polished and complete document!

The use cases for the feature nicely setup the case for the spec: 
* Restrictive or Too-Specific use cases for previously defined sensor APIs (for example, some APIs are very "high level" -- not bad in themselves, but may not address other potential "low level" uses of the sensor)
* Fragmentation on the ways sensors are exposed (e.g., various API proposals of different shapes/forms)

Scoping seems appropriate:
* Scoped to local sensors (not remote or network-based)
* No sensor discovery mechanism (limited number of sensors does not warrent it--usually only one sensor in a device per type)
  * Feature detection is the discovery mechansim for now.
* What are the scope/extents of what are considered local sensors?
  * Would be nice to see a few specifics in the Scope section. (Hinted in some examples, like Geolocation, Automotive--Ex.2, Ambient light--Ex.3, Proximity--Ex.3, Gyroscope--Ex.3)

General Thoughts:
* (plus) Unification of exposure to the web platform. Brings consistency and cohesiveness to the developer experience.
* (concern) Would it be enough motivation to transition from legacy APIs like legacy geolocation? Has this come too late?

Feature detection section was very nice! 
* Expand on the example here! Add more examples. I was confused at first since it's not clear what might be throwing and why, which let me to think it was the constructor (still not sure about that). 
  * On throwing in general: does it really help with the problems described? E.g., status of underlying hardware changing over time? Try/catch seems a pretty heavy-handed detection model compared to notification via events, but perhaps there some other reason why?

Note about Fingerprinting:
* On mitigating fingerprinting risk by limiting event rates: May not be necessary. Might be nice to suggest that the UA offer a user-control to disable the sensor for privacy reasons? 
* See: section 4 of [Unsanctioned Tracking](http://www.w3.org/2001/tag/doc/unsanctioned-tracking/#limitations-of-technical-solutions):

> In this environment, it is impractical for specification design to eliminate fingerprinting; not only would such restriction severely hobble the capability of the Web, it would also break a substantial amount of existing content. Moreover, theory confirms that we cannot expect to eliminate these problems on a general-purpose system: From a theoretical perspective, eliminating browser fingerprinting is essentially the same problem as eliminating covert channels [confinement].
>
> As a result, we cannot solve the issues that unsanctioned tracking raises through solely technical means. At times, they may be more appropriately addressed through policy (e.g., legislation and/or regulation).

Section 5.1:
* Limitation to top-level browsing context. Is this overly constrained?

Nice work and good taxonomy of low-level vs high-level (described by their readings [high level] or by their implementation [low level] )

Section 8.2 SensorReading
* DOMHishResTimeStamp -- this is generally useful for other web performance metrics... we should consider adding this to Event().

Section 8.4 SensorErrorEvent
* Should Error type rather be DOMException? (https://github.com/w3ctag/spec-reviews/issues/88)?

Section 9.1
* Incumbant Settings Object should not be used (see big red note in the link to it in HTML) and https://www.w3.org/Bugs/Public/show_bug.cgi?id=26603.

**Comment by travisleithead** [comment]
We believe that @tobie has acknowledged this feedback. As such closing. Tobie, if you are expecting further details, feel free to reactivate 😄.

**Comment by tobie** [comment]
Thanks for the comments @travisleithead. Unfortunately, as [detailed here](https://lists.w3.org/Archives/Public/public-device-apis/2016Jun/0041.html), my involvement with this spec has been on hold as of late. Will include your feedback once this is resolved.
