### ISSUE TITLE
Question: Should spec-review discussions live inside respective spec's repository?

### ISSUE THREAD

**Issue by JakeChampion** [w3ctag/spec-reviews#112]
### Problem:
A developer who actively follows specifications issues was not aware of a potential issue with a specification.

### Description:
I actively follow the repositories of specifications that I'm interested in such as [Fetch](https://github.com/whatwg/fetch), [webRTC](https://github.com/w3c/webrtc-pc), and [ServiceWorker](https://github.com/slightlyoff/ServiceWorker) as to read issues with the specifications and any new proposals.

I only found out today about this repositories existence due to a colleague who is in the TAG and asked for opinions on the [Fetch API "WithCredentials" flag issue](https://github.com/w3ctag/spec-reviews/issues/76).

### Proposed Solution:
If a specification already has it's own repository (on Github or similar) which can have issues created, create an issue in it's repository about the potential issues found during a spec-review. I imagine it would get more community involvement as developers who are interested in the spec may be watching the repositories issues.

**Comment by torgo** [comment]
Discussed at [London f2f](https://github.com/w3ctag/meetings/blob/gh-pages/2016/03-london/agenda.md).

Jake - thanks for the feedback, which we've taken on board. However as we discussed today at out f2f : 

1. The issues are here because this issue list is about organizing our work and discussion.
2. A TAG discussion on another spec might be specific to TAG work and not necessarily an issue with that spec
3. If we link our issue to another issue in a different repo then that at least makes it visible that this discussion is happening here which could address the root concern
4. We've asked people to raise an issue in this repo if they want the TAG to review something so it makes sense for discussion to happen here at least initially.
5. We're happy to break out stuff into issues in others' spec, but initially it makes sense to have discussion happen here

Suggest we can close the issue on this basis?

**Comment by JakeChampion** [comment]
I think this issue can be closed if items 3 & 5 are being done.

An example would be https://github.com/w3ctag/spec-reviews/issues/76 looks to be related to https://github.com/whatwg/fetch/issues/264 but no explicit linking of those issues has happened.

**Comment by torgo** [comment]
@JakeChampion and that's definitely an oversight on our part - so thank you for kicking us about it. :)

**Comment by torgo** [comment]
closing for now but this has now been updated on our readme to remind us to keep doing this
