### ISSUE TITLE
Accelerated Mobile Pages (AMP)

### ISSUE THREAD

**Issue by torgo** [w3ctag/spec-reviews#122]
The [AMP project](https://www.ampproject.org/) is encouraging some developer practices which enable high performance mobile web applications. But are these practices compatible with web architectural principles?

**Comment by triblondon** [comment]
I have two concerns:

1. Ecosystem creation: AMP is a big bottle of kool-aid and you have to drink the whole thing. It's "the AMP way or the highway".  This is nothing new, and could be said of any framework that creates an opinionated way of doing everything and makes it hard, awkward or impossible to do things in other ways - Ember, React, Angular could probably all be considered ecosystems in that sense too.  But given the internal architectural design of AMP, it seems a chronic shame that some of the benefits (eg amp-img) cannot be used by sites not willing to sign up to go 'full AMP'.  I'm not sure this is an architectural concern for the web though, it just limits the benefits of AMP (which no doubt will be widely adopted anyway simply because it offers more Google juice)

2. Canonical content: The severe constraints imposed by AMP make it very hard to operate a major website that is AMP compliant.  For example, even adding a comment form at the bottom of the page is not possible.  This will invariably lead to every page that is published as AMP also being available in a non-AMP form with more features, and the AMP project anticipates this.  This may be more of an architectural concern for us if it becomes common practice to publish multiple variants of the same page, at different URLs.

**Comment by triblondon** [comment]
happy to close this if there is no interest.  I raised an issue on the AMP project suggesting that AMP components could be available outside of the AMP ecosystem, and got a thoughtful response that basically amounts to 'no':

https://github.com/ampproject/amphtml/issues/3453

**Comment by torgo** [comment]
Discussed [06 July](https://github.com/w3ctag/meetings/blob/gh-pages/2016/telecons/07-06-agenda.md) - canonical URLs one concern, "ecosystem" and tooling another.

**Comment by torgo** [comment]
Agreed to close and take the canonical URL concern into new issue to be created on that topic.
