### ISSUE TITLE
Review request for Scroll Anchoring

### ISSUE THREAD

**Issue by KenjiBaheux** [w3ctag/spec-reviews#142]
Spec: https://cdn.rawgit.com/WICG/interventions/master/scroll-anchoring/spec.html

Abstract:
Changes in DOM elements above the visible region of a scroller can result in the page moving while the user is in the middle of consuming the content.

This spec proposes a mechanism to mitigate this jarring user experience by keeping track of the position of an anchor node and adjusting the scroll offset accordingly.

This spec also proposes an API for web developers to opt-out of this behavior.

---

Context: we've reached a point where we are confident in our design and have run out of known web compatibility issues. The next logical step would be to try shipping this, listen for feedback and iterate if needed. We would like to request a TAG review for the spec. The current timeframe we are aiming for is: Chrome 56 (branch cut: Nov 17th, 2016).

Thanks in advance.

**Comment by triblondon** [comment]
2.1, step 2, third bullet:

> If N is fully clipped in S, skip over E and its descendents.

There is no definition of `E`

**Comment by travisleithead** [comment]
Also, see explainer: https://github.com/skobes/ScrollAnchoring/blob/master/explainer.md

**Comment by skobes** [comment]
Thanks @triblondon, I have fixed the typo in 2.1 and added a link to the explainer.

The suppression triggers are mainly to handle pages that implement various forms of "sticky headers".  In the simplest case, script simply toggles position:fixed on a header element below a scroll offset, causing the content to shift by pulling it out of flow.  We've also seen animation on document body padding at the transition.  See e.g. http://crbug.com/601906 and http://crbug.com/641814.

I think the reuse of overflow-anchor makes sense because scroll anchoring and sticky scrollbars are two alternative strategies for connecting scroll position to layout.  It wouldn't make sense to want both at the same time.

The infinite-scroller content loop is an interesting idea, we haven't encountered scenarios like this in practice.  Typically a scroll-triggered content load inserts at the bottom and not the top.

**Comment by triblondon** [comment]
Picked up at TAG F2F in Boston.  I'm still concerned about the potential for inconsistency from a developer perspective.  A common pattern is to animate open a zero-height element containing an ad when the viewport encounters the placeholder.  If that element is in the ancestry of the anchor node (eg if it is the document body) then scroll anchoring is suppressed, whereas if it is not, scroll anchoring is activated.  It's not a huge problem, but it may confuse people initially.

Otherwise LGTM, and I'm (still) excited about having this feature :-)

**Comment by RByers** [comment]
For reference, current spec and explainer are at: https://github.com/WICG/ScrollAnchoring
