### ISSUE TITLE
CSS Variables

### ISSUE THREAD

**Issue by torgo** [w3ctag/spec-reviews#41]
http://dev.w3.org/csswg/css-variables/

**Comment by mnot** [comment]
Discussed in SF; -- syntax still there. Variables in CSS not easily settable in script. Observing variable changes is difficult. @plinss to write up.

**Comment by torgo** [comment]
From Berlin f2f: @travisleithead thinks it's fine.

**Comment by slightlyoff** [comment]
I'd like to note that the lack of an API is disappointing. I know there's work to get it done, but I don't understand the current state and would like to see it prioritized.

**Comment by tabatkins** [comment]
Getting/setting API is absolutely there - they're *properties*, so you just use the normal property API.  Because of naming, you can't use the easy `style.foo` API, but `style.getPropertyValue()` is an old and well-established API.

Observing changes is indeed difficult, and is being addressed in Houdini <http://drafts.css-houdini.org/css-properties-values-api/>.  Getting Variables out the door required keeping it extremely lean; it was the very first extension point CSS had ever grown!
