### ISSUE TITLE
Presentation API Request for Feedback

### ISSUE THREAD

**Issue by torgo** [w3ctag/spec-reviews#61]
François has requested our feedback https://lists.w3.org/Archives/Public/www-tag/2015Jul/0001.html on the presentation API: https://w3c.github.io/presentation-api/

**Comment by travisleithead** [comment]
Draft review up at: [Presentation API review](https://github.com/w3ctag/spec-reviews/blob/master/2015/presentation-api.md)

**Comment by travisleithead** [comment]
Ran out of time on some of the questions at the end :-(

**Comment by torgo** [comment]
Discussed at [call on 29 July 2015](https://github.com/w3ctag/meetings/blob/gh-pages/2015/telcons/07-29-presentationAPI-agenda.md).

**Comment by torgo** [comment]
Would like to see feedback on this document... @slightlyoff? Schedule a future session specifically on this with members of the 2nd screen working group...?

**Comment by torgo** [comment]
let's work towards agreeing the feedback for the 12th.

**Comment by travisleithead** [comment]
Consider reformatting in terms of questions back to the group (to facilitate a conversation with them later)

**Comment by domenic** [comment]
FWIW I really liked the review. The call for unification with existing features was very nice.

**Comment by torgo** [comment]
Taken up at Boston f2f. Question for @tidoust - is additional feedback still sought / useful?

**Comment by tidoust** [comment]
Thanks for pinging me @torgo. For some reason, I had managed to miss that issue entirely, sorry about that and many thanks for the timely review!

So first, I'll point the Second Screen WG to it. We'll get back to you if needed as we process that feedback.

**Comment by travisleithead** [comment]
Review with the SSWG scheduled for TPAC week on Thursday.

**Comment by travisleithead** [comment]
Review went well today. The Second Screen WG had some followup from the discussion that I would like to bring back to the TAG:
* The SSWG would like to reference the TAG's [Private Mode](http://w3ctag.github.io/private-mode/) 
spec under the expectation that Private Mode would define how to start up a browsing context in a "clean state" (e.g., empty database, local storage, cookies, etc.). If the document would be able to define that (and be ready in a reasonable time), then it may be reasonable for the Second Screen spec to reference it. Otherwise (and perhaps more likely?), the Second Screen spec would need to be explicit in what states it expects the various features it cares about to be in. Either way, we need to reply back with our suggestion after discussing this.
* We identified a somewhat interesting issue that is manifest when you start launching browsing contexts on screens where there is either no facility for processing user input, or no user nearby (i.e., a second screen connection to a "smart" projector). In these cases, some parts of the web platform are not workable when no user is available. ```window.alert()``` is one such example--a blocking API that requires a user to dismiss the UI. Another example is the ```input.type=file``` when it is ```click()```-ed. (Other things that require user interaction or user consent are generally designed for async behavior and can tolerate not being responded to.) We felt this was an opportunity for collaboration between the Web Platform WG and the SSWG. As the TAG, let's make this happen.

**Comment by travisleithead** [comment]
Discussed at 2 Dec 2015 telecon: raw minutes: https://pad.w3ctag.org/p/02-12-2015-minutes.md

**Comment by travisleithead** [comment]
Write up our comments from the above-mentioned telecom, and deliver :)

**Comment by travisleithead** [comment]
> The SSWG would like to reference the TAG's Private Mode spec under the expectation that Private Mode would define how to start up a browsing context in a "clean state" (e.g., empty database, local storage, cookies, etc.). If the document would be able to define that (and be ready in a reasonable time), then it may be reasonable for the Second Screen spec to reference it. Otherwise (and perhaps more likely?), the Second Screen spec would need to be explicit in what states it expects the various features it cares about to be in. Either way, we need to reply back with our suggestion after discussing this.

@tidoust, @anssiko: At our most recent TAG f2f we discussed an alternate approach to our previously planned "privacy mode" spec. Given some pushback from implementers against standardizing the specifics of what constitutes privacy mode in browsers directly, @mnot has proposed a document that may be an incremental step toward that eventual goal. The document, aimed at spec authors, should provide a framework from which to consider the various user data controls that are made available in browsers. It is our hope that such a document could be a good reference for any spec concerned with how their feature is impacted by user privacy concerns. As the Second Screen group gave the TAG specific feedback about wanting to reference a privacy mode spec, we hope you'll take a look at this document and provide us feedback on whether it would be useful to you as a reference.

https://gist.github.com/mnot/96440a5ca74fcf328d23

Thanks so much!

**Comment by anssiko** [comment]
@travisleithead @mnot Thanks! We're now tracking this in https://github.com/w3c/presentation-api/issues/275 and will provide you with feedback (we might synthesize the feedback at the SSWG's May F2F, so it might take a while for us to get back to you).

**Comment by anssiko** [comment]
Fixed TAG's "privacy mode" feedback (w3c/presentation-api#275) with w3c/presentation-api#308.

Also, @annevk's feedback initially triggered by this TAG review (tracked in w3c/presentation-api#153) is being addressed by rechartering and bringing back to life the Second Screen Community Group: 

https://webscreens.github.io/cg-charter/
https://github.com/webscreens/cg-charter/

**Comment by travisleithead** [comment]
Excellent. Thanks @anssiko. Seems like all the feedback has been incorporated (in both directions). I'll close this issue now. If you want any further reviews/followup, feel free to reach out again with a new issue.
