### ISSUE TITLE
Motion path spec

### ISSUE THREAD

**Issue by shans** [w3ctag/spec-reviews#66]
https://drafts.fxtf.org/motion-1/
- Outstanding issues inline.
- Blink I2I: https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/uqDmsIj6zJY/cS-Vp_XG2oYJ
- Blink I2S: https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/N4o2MoV1zuw

**Comment by slightlyoff** [comment]
Are there specific areas of concern that you'd like for us to pay attention to, over and above the issues you linked to?

**Comment by dbaron** [comment]
Some comments:

It seems like it should say more explicitly that it works like the 'transform' property (which I think is the intent).  For example, having 'motion-path' should have the effects that 'transform' has like creating a stacking context, being a containing block for absolute and fixed positioned elements, etc.

It also seems like the spec should have some examples with code in them.

**Comment by dbaron** [comment]
Also, the "Applies to" is a little suspicious in terms of being broader than the "transformable elements" set in the CSS Transforms spec.

**Comment by slightlyoff** [comment]
A few thoughts:

 * There don't appear to be any meaningful examples in the spec. Had to go dig them out of the Chromium repo (here)[https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/LayoutTests/css3/motion-path/&q=motion-offset&sq=package:chromium&type=cs]. This is a pretty big issue.
 * The `transform-box` which is the root of the transformation [is spec'd](https://drafts.csswg.org/css-transforms-1/#transform-box) but appears to be a new property with uncommon semantics. Why was this chosen instead of a more locally-familiar coordinate system?
 * It seems the interactions with layout aren't called out well. I.e., these things create stacking contexts, become containing blocks, etc., no?

**Comment by plinss** [comment]
These properties have been merged with polar positioning and are currently in the Round Display spec:
https://drafts.csswg.org/css-round-display/#positioning-content

The motion path spec needs to be tombstoned.

**Comment by shans** [comment]
During the SF face-to-face I thought we had resolved to merge the round display properties into motion-path, not the other way around. Has something changed since?

**Comment by plinss** [comment]
Only that the current work seems to be happening in the Round Display spec. I expect it will get moved back to motion-path at some point (or possibly another spec). I don't care where it ends up (or lives now) and am not advocating for any location, I just think it's confusing to have conflicting work in two places, and one of them should just point to the other.
