### ISSUE TITLE
Feedback on Keygen

### ISSUE THREAD

**Issue by plinss** [w3ctag/spec-reviews#82]
Discuss Travis's draft response
https://github.com/w3ctag/meetings/wiki/DRAFT-response-on-keygen-for-TAG-consideration

**Comment by travisleithead** [comment]
Plan:

1. cleanup the doc
2. incorporate feedback
3. create a new repo for this doc and move it there (to consolidate issues)
4. ensure Tim is aware of the feedback
5. post to www-tag

**Comment by torgo** [comment]
Hi Travis any update on this? Shall we put it on the agenda for this week?

**Comment by travisleithead** [comment]
I did not, unfortunately, get to this prior to TPAC as I had hoped to do. I’ve been planning to return to it all last week, and again, it got postponed due to a variety of internal activities. I’ve got some time scheduled tomorrow and later today to work on it, but don’t expect to have anything substantive ready to discuss at our call. In the best case, I can point to an updated draft of what I plan to send.

Thanks!

**Comment by torgo** [comment]
taken up 11-11. @travisleithead incorporating some feedback Hope to have out by end of week.

**Comment by travisleithead** [comment]
Document is up: https://w3ctag.github.io/client-certificates/
Mail has been sent: http://lists.w3.org/Archives/Public/www-tag/2015Nov/0000.html
