### ISSUE TITLE
Network Information API

### ISSUE THREAD

**Issue by igrigorik** [w3ctag/spec-reviews#86]
- http://w3c.github.io/netinfo/
- http://caniuse.com/#feat=netinfo

**Comment by mnot** [comment]
Discussed at the Melbourne F2F. 

In terms of API design, this seems reasonable. We understand that there are a number of trade offs in this design space, and that there is some risk here. However, we feel that publishing something in this space is generally good, because it meets a significant need in the platform -- even if it is not initially perfect. 

We'd encourage you to continue to gather information from developers and discuss it with other implementers. 

Also, the information at the current version link in /TR should be updated to reflect status.

**Comment by igrigorik** [comment]
Great, thanks! I'll try to get the TR updated.
