### ISSUE TITLE
Review Web Annotations specs

### ISSUE THREAD

**Issue by travisleithead** [w3ctag/spec-reviews#93]
@slightlyoff: We'd be happy to dig in and understand these specs. Perhaps we could chat in an upcoming TAG call to get better acquainted?

>The Web Annotation WG is scheduled to meet at TPAC on Monday and Tuesday, 26-27 October. I see that the TAG is [scheduled for one day, Monday 26 October](http://www.w3.org/2015/10/TPAC/schedule.html).
>
>It might be useful to schedule some time for a joint session on Monday to discuss two Web Annotation WG deliverables to socialize them and get early feedback on the architectural approach.
>
>(1) [Web Annotation Protocol](http://www.w3.org/TR/2015/WD-annotation-protocol-20150702/)
>
>One of the deliverables of the Web Annotation WG is a Web Annotation protocol. Some questions were raised earlier about the RESTful nature of the specification.
>
>(2) [FindText](http://w3c.github.io/findtext/)
>
>We'd appreciate general feedback (by TPAC this should be a FPWD, but we can make changes to subsequent WDs)
>
>Would it be possible to schedule a session with the TAG on Monday to review/discuss the protocol spec? If so, when might be possible times?
>
>Thanks
>regards, Frederick

**Comment by torgo** [comment]
taken up 11-11

**Comment by mnot** [comment]
Some initial notes:

* This specification is effectively profiling HTTP by using language like "The server must support the following HTTP methods on the Annotation Container's URI." It should just describe the representations and interaction expectations upon resources that use them.
* Likewise, it's very MUST/SHOULD heavy; when specs overuse the RFC2119 terms, it doesn't help readability or interoperability.
* "When a paging preference is received, instead of returning the representation of the container, the server must return a response with the status code of 303 and a Location header with the URI for the first page." What if the user isn't authorised? What if other parts of the request are malformed? What if the resource doesn't exist? MUSTs like this are seldom helpful.
* 5. Error Conditions creates application-specific semantics for standard HTTP status codes. This is an anti-pattern; the point of HTTP status codes is that any application (including intermediaries) can understand them; application-specific semantics belong in the payload.

**Comment by torgo** [comment]
Picked up in teleconf 25-November-2015: https://github.com/w3ctag/meetings/blob/gh-pages/2015/telcons/11-25-agenda.md

**Comment by mnot** [comment]
Discussed in Melbourne F2F; reminded ourselves that we need to arrange a discussion with one or more folks from the Annotations community about this spec.

**Comment by iherman** [comment]
See https://github.com/w3c/web-annotation/issues/313#issuecomment-229681515 for a more complete, and up-to-date response of the WA Working Group

**Comment by torgo** [comment]
Discussed on [6 July Call](https://github.com/w3ctag/meetings/blob/gh-pages/2016/telecons/07-06-agenda.md)

**Comment by torgo** [comment]
Seems we need to feed back on https://github.com/w3c/web-annotation/issues/313#issuecomment-229681515. Pending feedback from @mnot....
