### ISSUE TITLE
Web Background Sync API

### ISSUE THREAD

**Issue by mkruisselbrink** [w3ctag/spec-reviews#95]
https://wicg.github.io/BackgroundSync/spec/

Implemented in chrome behind a flag (https://www.chromestatus.com/features/6170807885627392), proposed in the WICG at https://discourse.wicg.io/t/proposal-for-a-web-background-sync-api/1118

**Comment by dbaron** [comment]
Are there any issues you (for all "you", really) are aware of that you think are particularly interesting for the TAG to look into, or that raise any architectural or cross-specification issues?

**Comment by mkruisselbrink** [comment]
Sorry for the slow reply. I'm not sure if there is anything specific here. The privacy considerations in the spec are maybe something that applies more generally to other specs as well (in particular things like sendBeacon and some of the CSP related reporting specs, which all do some kind of background network activity to websites for which all windows have been closed already). 
Maybe @jkarlin has any other ideas.

**Comment by jkarlin** [comment]
I don't know of any particular issues.

**Comment by mnot** [comment]
Discussed at the Melbourne F2F.

Overall, we're in favour of what you're doing here.

The document doesn't enumerate its error conditions; it would be nice if this was spelled out, or at least shown more in example code.

E.g., consider the situation when a service worker is woken up to do background sync, and inside that you register for another background sync; what are the implications -- should a UA allow that? How should they notify the user? Are there normative limitations, and if not, are there heuristics?

It would be great if there was an "explainer" document to show how to use background sync, and discussing some of the design decisions.

Allowing a browser to do things after a page is closed open a number of new issues, because users' mental models for the Web doesn't include this. For example, privacy (as discussed), power usage, bandwidth usage, etc. It would be really helpful if there were a separate document exploring these concerns and talking about potential mitigations; this would help not only users and implementers of background sync and future extensions to it, but also other features that have similar concerns (e.g., beacon, web push). The spec could then link to this document to help implementers.

Would you consider writing such a document?

**Comment by jkarlin** [comment]
Thanks @mnot. There is an [explainer](https://github.com/WICG/BackgroundSync/blob/master/explainer.md) up. I've created issues to address your other comments.

**Comment by mnot** [comment]
Thanks. Ping us if you have any questions / want more review.
